module.exports = {
    tabWidth: 2,
    useTabs: false,
    semi: true,
    singleQuote: true,
    quoteProps: 'consistent',
    jsxSingleQuote: false,
    trailingComma: 'all',
    bracketSpacing: true,
    jsxBracketSameLine: false,
    arrowParens: 'avoid',
    rangeStart: 0,
    rangeEnd: Infinity,
    vueIndentScriptAndStyle: false,
    endOfLine: 'lf',
    // parsers: {
    //   '.jsx': 'flow',
    //   '.scss': 'scss',
    //   '.ts': 'typescript',
    //   '.less': 'css',
    //   '.vue': 'vue',
    //   '.nvue': 'vue',
    //   '.ux': 'vue',
    //   '.yml': 'yaml',
    // },
};
